---
name: Git Tag Push Example
namespace: examples
labels:
  label1: value1
  label2: value2
steps:
  - name: Do something
    tasks:
    - name: Task 1
      action: webhook
      arguments:
        url: https://www.google.com
      retries: 0
      timeout: 5
      verify_ssl: true
  - name: Do something else
    tasks:
    - name: Task 2
      action: webhook
      arguments:
        url: https://www.google.com
      retries: 0
      timeout: 5
      verify_ssl: true
    - name: Task 3
      action: webhook
      arguments:
        url: https://www.google.com
      retries: 0
      timeout: 5
      verify_ssl: true
notifiers:
  - name: Send Slack notification
    notifier: example.slack-example
    arguments:
      key_1: value
      key_2: value
    events: complete
rules:
  mode: all
  name: git_tag_push
  rules:
  - invert_match: false
    label_name: git.event
    label_value: tag_push
    match_mode: exact
    name: Tag push event
...
