---
name: rocketchat
namespace: generic
type: webhook
properties:
  url: "https://rc.clarkinc.biz/hooks/5hh6xquqfcByp47ac/wXu5GsakusR7M6k7Zo4wTH7ZFwfy9R55Qzk6gZPWotTbFzXm"
  body: '{"username":"[msg]","text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":":+1: The job worked!","image_url":"https://rocket.chat/images/mockup.png","color":"#764FA5"}]}'
  method: "POST"
  headers:
    "Content-Type": "application/json"
...
